### ISSUE TITLE
Regarding /proc/sys/net/core/somaxconn

### ISSUE THREAD

**Issue by buzzcut-s** [clearlinux/clr-power-tweaks#22]
Is setting a value of 512 (https://github.com/clearlinux/clr-power-tweaks/blob/master/src/data.h#L65) here still necessary? 

Upstream changed it to 4096 in 5.4 , refer https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=19f92a030ca6d772ab44b22ee6a01378a8cb32d4.

So why not just use the kernel default? Any insights would be appreciated. Thank you!

**Comment by ahkok** [comment]
I totally support taking the whole line just out. @fenrus75 ?

**Comment by fenrus75** [comment]
yeah totally fine

128 was too little... that's why we bumped it

**Comment by ahkok** [comment]
Consider it done.

**Comment by ahkok** [comment]
c0182599b63ce11fe133e6ad4bf42807f796639a
