### ISSUE TITLE
Heads up: 5.13 will move some sysctl tunables

### ISSUE THREAD

**Issue by insilications** [clearlinux/clr-power-tweaks#24]
These and others will be moved to debugfs:
No match for pattern "/proc/sys/kernel/sched_min_granularity_ns"
No match for pattern "/proc/sys/kernel/sched_migration_cost_ns"
No match for pattern "/proc/sys/kernel/sched_wakeup_granularity_ns"

All of these will be accessed through:

/sys/kernel/debug/sched/min_granularity_ns
/sys/kernel/debug/sched/migration_cost_ns
/sys/kernel/debug/sched/wakeup_granularity_ns

https://lore.kernel.org/patchwork/patch/1414718/
https://www.spinics.net/lists/kvm/msg242173.html

**Comment by phmccarty** [comment]
Thanks for the notice. I suppose we need to add runtime checks for the kernel version to support both old and new locations...

**Comment by fenrus75** [comment]
as we're moving to 5.13 nowish... thanks for the heads up.

It's also a good time to consider if we want these still... will run some experiments
