### ISSUE TITLE
Laptop stuck at performance governor

### ISSUE THREAD

**Issue by davidqge** [clearlinux/clr-power-tweaks#28]
My laptop fan blowing because of perfoamance governor.

Distribution:      Clear Linux OS
Installed version: 39930
6.1.52-1312.ltscurrent

cat /sys/devices/system/cpu/cpufreq/policy0/scaling_available_governors
ondemand performance schedutil

There is no more powersave governor. 

according to: https://www.kernel.org/doc/Documentation/cpu-freq/governors.txt
schedutil is better suited than powersave, which stuck at minimum freq.

**Comment by fenrus75** [comment]
thanks for the report --- fixing up this now

**Comment by davidqge** [comment]
works on version 40060.

Thank you!
